### PR TITLE
Make CoreFX/Native be valid C++.

### PR DESCRIPTION
**Pull request by jaykrell**
- Assignment from void* to non-void.
    Add cast.
 - sizeof_member(struct foo, bar)
   Add typedef struct foo foo and remove struct in member_sizeof.

### CODE REVIEW

**Comment by jaykrell** [comment]
Submitted upstream as https://github.com/dotnet/corefx/pull/31342.

**Comment by marek-safar** [comment]
We are not going to switch PAL to C++

**Comment by jaykrell** [comment]
Just valid C++ is useful, to alleviate hacking of Makefile.am in mono/metadata, so the entire directory can be C++ instead of individual libraries.

Did anyone look at how trivial the diffs are?

**Comment by marek-safar** [comment]
We are trying to have a minimal diff of changes in our fork. Making it C++ compatible is right now definitely out of that list. You can push that upstream if you want but don't see any reason to maintain it here

**Comment by jaykrell** [comment]
ok I did https://github.com/dotnet/corefx/pull/31342
Notice that the second change is just tracking upstream, which we are way behind.

**Pull request closed without merging**
