### PR TITLE
Add types supporting C# 8.0 Ranges.

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by marek-safar** [comment]
Does this change also include https://github.com/dotnet/coreclr/pull/22331 ?

**Comment by baulig** [comment]
I cherry-picked the commits from `corefx/master`, not `coreclr` and it looks like that coreclr change has not made it into corefx yet.

**Comment by baulig** [comment]
It looks like we're still missing https://github.com/dotnet/corefx/pull/35003 or something like this?

Tests are currently failing with lots of

```
/Workspace/mono-testing/external/corefx/src/System.Memory/tests/Span/Indexer.cs(35,52): error CS0117: 'Range' does not contain a definition for 'Create'
```

**Comment by baulig** [comment]
Looks like this is going to land as part of https://github.com/dotnet/corefx/pull/35207.

**Pull request merged**
